package GUI;

import java.awt.Toolkit;
import java.io.PrintStream;
import Negocio3.Facade;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pedro
 */
public class ApresentaResultados extends javax.swing.JFrame {
    Facade facade = new Facade();
    int idEleicao;
    /**
     * Creates new form ApresentaResultados2
     */
    
    public ApresentaResultados() {
        this.idEleicao = 0;
        initComponents();
        setIcon();
        jTextArea1.setText("ERRO: idEleicao da janela é 0.");
        jTextArea1.setEditable(false);
    }
    public ApresentaResultados(int idEleicao) {
        this.idEleicao = idEleicao;
        initComponents();
        setIcon();
        if(facade.getTipoEleicao(idEleicao)> 1 && facade.getTipoEleicao(idEleicao)<5){
            if(facade.getTipoEleicao(idEleicao)==2){
            jTextArea1.setText(facade.geraResultadoTotalAssembleiaRepublica(this.idEleicao));
            jTextArea1.setEditable(false);
            facade.finalizarEleicaoBD(idEleicao);
            } else {
                if(facade.getTipoEleicao(idEleicao)==4){
                    jTextArea1.setText(facade.geraResultadoTotalAssembleiaAçores(this.idEleicao));
                    jTextArea1.setEditable(false);
                    facade.finalizarEleicaoBD(idEleicao);
                }
                else {
                    jTextArea1.setText(facade.geraResultadoTotalAssembleiaMadeira(this.idEleicao));
                    jTextArea1.setEditable(false);
                    jButton1.setVisible(false);
                    jButton1.setText(" ");
                    facade.finalizarEleicaoBD(idEleicao);
                }
            }
        }
        else{
           if(facade.getTipoEleicao(idEleicao)==1){
            jTextArea1.setText(facade.geraResultadoPresidencial(this.idEleicao));
            jTextArea1.setEditable(false);
            jButton1.setVisible(false);
            jButton1.setText(" ");
            facade.finalizarEleicaoBD(idEleicao);
           } else{
               jTextArea1.setText("Dados da Eleição está inscosistence!");
            jTextArea1.setEditable(false);
           }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestor de Eleições");
        getContentPane().setLayout(null);

        jButton1.setText("Ver Resultados Por Círculo Eleitoral");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 480, 220, 30);

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(680, 480, 70, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 100, 590, 370);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Resultados");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 50, 150, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pictures/winner_back.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 790, 540);

        setSize(new java.awt.Dimension(805, 566));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JanelaAdministrador janadmin = new JanelaAdministrador();  
        janadmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ConsultarCirculoEleitoralDistritoAdmin consuldistr = new ConsultarCirculoEleitoralDistritoAdmin(idEleicao);
        consuldistr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApresentaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApresentaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApresentaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApresentaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApresentaResultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/GUI/pictures/admin_icon.png")));
    }

}
