/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import Negocio3.Facade;

/**
 *
 * @author pedro
 */
public class AssociarCirculoEleitoralIlhas extends javax.swing.JFrame {

    
    private final int id;
    private final int idCabeca;
    private int ilha;
    /**
     * Creates new form AssociarCirculoEleitoralIlhas2
     */
    
    public void mostrarilhas(){
        try{
        String funcao = this.jList1.getSelectedValue().toString();
        //Ilha de S.Miguel, Ilha Graciosa,  Ilha da Terceira, Ilha do Faial, Ilha do Pico,Ilha das Flores,Ilha do Corvo,Ilha de S.Jorge,Ilha de Sta.Maria
        switch(funcao){
            case("Ilha do Corvo"):
                AssociarCirculoEleitoralIlhas.labelilhas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pictures/corvo.png")));
                ilha=28;
                break;
            case("Ilha das Flores"):
                AssociarCirculoEleitoralIlhas.labelilhas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pictures/flores.png")));
                ilha=27;
                break;
            case("Ilha Graciosa"):
                AssociarCirculoEleitoralIlhas.labelilhas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pictures/graciosa.png")));
                ilha=23;
                break;
            case("Ilha de Sta.Maria"):
                AssociarCirculoEleitoralIlhas.labelilhas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pictures/santamaria.png")));
                ilha=30;
                break;
            case("Ilha de S.Miguel"):
                AssociarCirculoEleitoralIlhas.labelilhas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pictures/s.miguel.png")));
                ilha=22;
                break;
            case("Ilha da Terceira"):
                AssociarCirculoEleitoralIlhas.labelilhas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pictures/terceira.png")));
                ilha=24;
                break;
            case("Ilha do Faial"):
                AssociarCirculoEleitoralIlhas.labelilhas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pictures/faial.png")));
                ilha=25;
                break;
            case("Ilha do Pico"):
                AssociarCirculoEleitoralIlhas.labelilhas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pictures/pico.png")));
                ilha=26;
                break;
            case("Ilha de S.Jorge"):
                AssociarCirculoEleitoralIlhas.labelilhas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pictures/s.jorge.png")));
                ilha=29;
                break;
            default : ilha=0;
        }
        } catch (NullPointerException e){
            // FUCK IT
        }
    }
    
    public AssociarCirculoEleitoralIlhas() {
        initComponents();
        setIcon();
        this.id = 0;
        this.idCabeca = 0;
        this.ilha=0;
        System.exit(0);
    }

    public AssociarCirculoEleitoralIlhas(int id, int idCabeca)  {
        initComponents();
        setIcon();
        this.id = id;
        this.idCabeca = idCabeca;
        this.ilha=0;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        labelilhas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestor de Eleições");
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Associar a Círculo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 10, 250, 30);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Ilha de S.Miguel", "Ilha Graciosa", "Ilha da Terceira", "Ilha do Faial", "Ilha do Pico", "Ilha das Flores", "Ilha do Corvo", "Ilha de S.Jorge", "Ilha de Sta.Maria" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 130, 180, 130);

        jButton1.setText("Criar Lista");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 430, 140, 23);

        labelilhas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelilhas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pictures/acores.gif"))); // NOI18N
        getContentPane().add(labelilhas);
        labelilhas.setBounds(200, 60, 670, 430);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Selecione o circulo eleitoral correspondente ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 40, 390, 20);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pictures/candidato_back.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 533);

        setSize(new java.awt.Dimension(816, 572));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()){
           mostrarilhas();
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Facade facade = new Facade();
        this.mostrarilhas();
        int r = facade.idEleicaoAberta();
        if(r != -1){
            //this.jList1.getSelectedValue().toString().equals("null")
            if(ilha!=0){
            String funcao = this.jList1.getSelectedValue().toString();
            int cir = facade.getIdCirculo(funcao);
            facade.setCirculoEleitoralProvisorio(idCabeca, cir);
            facade.setCirculoEleitoral(idCabeca, ilha);
            facade.putLista(id, id, idCabeca, false, r);
            InscreveAssembleia ia = new InscreveAssembleia(id);
            ia.setVisible(true);
            this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null,"Escolha uma ilha");
                
            }
        }
        else{
            System.err.println("Mais que eleição em aberto, lista não foi criada");
            InscreveAssembleia ia = new InscreveAssembleia(id);
            ia.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssociarCirculoEleitoralIlhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssociarCirculoEleitoralIlhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssociarCirculoEleitoralIlhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssociarCirculoEleitoralIlhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssociarCirculoEleitoralIlhas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel labelilhas;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/GUI/pictures/icom.png")));
    }   

}
