/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import java.awt.Toolkit;
import javax.swing.JOptionPane;
import Negocio3.Facade;

/**
 *
 * @author pedro
 */
public class ConsultarEleicoesHistorico extends javax.swing.JFrame {
    
    Facade facade = new Facade();
    private final int idEleitor;
    private final int idEleicao;
    private final int tipo;
    private final boolean loginCandidato;
    /**
     * Creates new form ConsultarEleicoesPresidenciais2
     */
    public ConsultarEleicoesHistorico() {
        initComponents();
        setIcon();
        this.idEleitor = 0;
        JOptionPane.showMessageDialog(null,"Erro");
        this.idEleicao = 0;
        this.tipo = 0;
        this.loginCandidato = false;
        jTextArea1.setText("ERRO: idEleicao da janela é 0.");
        jTextArea1.setEditable(false);
        System.exit(0);
        
    }

    public ConsultarEleicoesHistorico(int idEleitor,int idEleicao,int tipo,boolean lc)  {
        initComponents();
        setIcon();
        this.idEleitor = idEleitor;
        this.idEleicao = idEleicao;
        this.tipo = tipo;
        this.loginCandidato = lc;
        if(facade.getTipoEleicao(idEleicao)> 1 && facade.getTipoEleicao(idEleicao)<5){
            if(facade.getTipoEleicao(idEleicao)==3){
                jButton1.setVisible(false);
                jButton1.setText(" ");
                jTextArea1.setText(facade.getHistoricoAssembleiaTotal(this.idEleicao));
            jTextArea1.setEditable(false);
            facade.finalizarEleicaoBD(idEleicao);
            } else {
            jTextArea1.setText(facade.getHistoricoAssembleiaTotal(this.idEleicao));
            jTextArea1.setEditable(false);
            facade.finalizarEleicaoBD(idEleicao);
            }
        }
        else{
           if(facade.getTipoEleicao(idEleicao)==1){
            jTextArea1.setText(facade.getHistoricoPresidencial(this.idEleicao));
            jTextArea1.setEditable(false);
            jButton1.setVisible(false);
            jButton1.setText(" ");
            facade.finalizarEleicaoBD(idEleicao);
           } else{
               jTextArea1.setText("Dados da Eleição está inscosistence!");
            jTextArea1.setEditable(false);
           }
        
    }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestor de Eleições");
        getContentPane().setLayout(null);

        jLabel2.setText("Eleições Histórico");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 30, 110, 50);

        jButton2.setText("Retroceder");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(653, 420, 90, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 90, 700, 290);

        jButton1.setText("Ver Detalhes por Círculo Eleitoral");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 410, 320, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/eleicoes.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 460);

        setSize(new java.awt.Dimension(777, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ConjuntoEleicoes conj = new ConjuntoEleicoes(tipo,idEleitor,loginCandidato);  
        conj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarEleicoesHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarEleicoesHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarEleicoesHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarEleicoesHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarEleicoesHistorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/GUI/pictures/icom.png")));
    }
}
