/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Toolkit;
import Dados3.DateUtils;
import GUI.JanelaAdministrador;
import javax.swing.JOptionPane;
import Negocio3.Facade;

/**
 *
 * @author pedro
 */
public class CriarEleicao extends javax.swing.JFrame implements DateUtils {

    /**
     * Creates new form CriarEleicao2
     */
    public CriarEleicao() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        dateChooserCombo1 = new com.toedter.calendar.JDateChooser();
        dateChooserCombo2 = new com.toedter.calendar.JDateChooser();
        dateChooserCombo3 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestor de Eleições");
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Criar Eleição");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 50, 130, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Tipo de Eleição");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 120, 140, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Fase Eleitoral");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 140, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Região Autonoma");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 230, 160, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Período de Candidatura");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 300, 200, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Data Inicio da Eleição");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(460, 140, 150, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Assembleia", "Presidencial" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(220, 120, 140, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-------", "Madeira", "Açores" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(220, 230, 120, 30);

        jButton1.setText("Retroceder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(523, 410, 120, 23);

        jButton2.setText("Criar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(670, 410, 90, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Inicio");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 270, 40, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Fim");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(460, 270, 60, 17);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 170, 90, 30);
        getContentPane().add(dateChooserCombo1);
        dateChooserCombo1.setBounds(220, 300, 190, 40);
        getContentPane().add(dateChooserCombo2);
        dateChooserCombo2.setBounds(450, 300, 170, 40);
        getContentPane().add(dateChooserCombo3);
        dateChooserCombo3.setBounds(460, 170, 180, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pictures/admin_back.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 450);

        setSize(new java.awt.Dimension(785, 490));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Facade f = new Facade();
        
        if((this.dateChooserCombo1.getDate().before(this.dateChooserCombo2.getDate())) && (this.dateChooserCombo2.getDate().before(this.dateChooserCombo3.getDate()))){
        
        int res=0;
        int idEleicao=0;
        //java.sql.Date(dateChooserCombo1.getCurrent().getTime());
        if(this.jComboBox3.getSelectedItem().toString().equals("-------"))res =1;
        if(this.jComboBox3.getSelectedItem().toString().equals("Madeira"))res =2;
        if(this.jComboBox3.getSelectedItem().toString().equals("Açores"))res =3;
        if(this.jComboBox1.getSelectedItem().toString().equals("Assembleia")){
            if (res==1) idEleicao = 2;
            if (res==2) idEleicao = 3;
            if (res==3) idEleicao = 4;
        }
        if(this.jComboBox1.getSelectedItem().toString().equals("Presidencial")) idEleicao = 1;
        //public void criarEleicao(int idFase, int regiaoAutonoma, LocalDate dt_IniE, LocalDate dt_IniC, LocalDate dt_fimC, int idTipo)
        f.criarEleicao(Integer.parseInt(jTextField1.getText()),res,asLocalDate(asSQLDate(this.dateChooserCombo3.getDate())),asLocalDate(asSQLDate(this.dateChooserCombo1.getDate())),asLocalDate(asSQLDate(this.dateChooserCombo2.getDate())),idEleicao);
        //JOptionPane.showMessageDialog(null, "Eleição Criada com sucesso");
        JanelaAdministrador janadmin = new JanelaAdministrador();  
        janadmin.setVisible(true);
        //JOptionPane.showMessageDialog(null, "Eleição Criada com sucesso");
        this.dispose();
        
        
        } else {
            JOptionPane.showMessageDialog(null,"Intervalo de datas introduzidas é inválida");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JanelaAdministrador janadmin = new JanelaAdministrador();  
        janadmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling co
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarEleicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarEleicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarEleicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarEleicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarEleicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateChooserCombo1;
    private com.toedter.calendar.JDateChooser dateChooserCombo2;
    private com.toedter.calendar.JDateChooser dateChooserCombo3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/GUI/pictures/admin_icon.png")));
    }
}
