/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.ConsultarEcra;
import GUI.VotarAssembleia;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import Negocio3.Facade;

/**
 *
 * @author pedro
 */
public class EcraEleitor extends javax.swing.JFrame {
    Facade facade = new Facade();
    
    private final int idEleitor;
    private final boolean loginCandidato;
    /**
     * Creates new form EcraEleitor2
     */
    public EcraEleitor() {
        initComponents();
        setIcon();
        this.idEleitor = 0;
        this.loginCandidato = false;
    }

    public EcraEleitor(int idEleitor,boolean lc) {
        initComponents();
        setIcon();
        this.idEleitor = idEleitor;
        this.loginCandidato = lc;
        this.jLabel7.setText(facade.getNomeEleitor(idEleitor));
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestor de Eleições");
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/login_alunos.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 150, 150, 170);

        jLabel3.setText("Utilizador:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 40, 60, 30);

        jLabel4.setText("Escolha uma das seguintes opções");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 100, 250, 30);

        jLabel5.setText("Votar");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 180, 100, 14);

        jLabel6.setText("Consultar Resultados");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 250, 160, 14);

        jButton1.setText("Escolher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 180, 120, 23);

        jButton2.setText("Escolher");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 250, 120, 23);

        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(435, 370, 120, 23);

        jLabel7.setText("Usuario");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 40, 430, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/eleicoes.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 410);

        setSize(new java.awt.Dimension(603, 448));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int r = facade.idEleicaoAbertaAVtoto();
        if(r==-1){
            JOptionPane.showMessageDialog(null, "Nenhuma eleição aberta à votos!");
        }else{
            int tipo = facade.getTipoEleicao(r);
            if(tipo==1&& !(facade.eleitorVotou(idEleitor))){
                //Precisdencial
                VotarPresidencial vp = new VotarPresidencial(idEleitor);//////////////////////////////////////////////// FAAAAAALTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA IDDDDDDDDDDDDDDDDDDDDD!
                vp.setVisible(true);
                this.dispose();
                

            }
            else{
                if(tipo<5 && tipo>1 && !(facade.eleitorVotou(idEleitor))){
                    if(tipo==3){ // Madeira
                        if(facade.getCirculoEleitoralEleitor(idEleitor)==21){
                            VotarAssembleia vass = new VotarAssembleia(idEleitor);  
                            vass.setVisible(true);  
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "O seu Círculo Eleitoral não corresponde ao Círculo da Região Autónoma Madeira");
                        }
                    }
                    if(tipo==4){ // Açores
                        if(facade.getCirculoEleitoralEleitor(idEleitor)>21 && facade.getCirculoEleitoralEleitor(idEleitor)<31){
                            VotarAssembleia vass = new VotarAssembleia(idEleitor);  
                            vass.setVisible(true);  
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "O seu Círculo Eleitoral não corresponde ao Círculo da Região Autónoma Açores");
                        }
                    }
                    if(tipo==2){
                        VotarAssembleia vass = new VotarAssembleia(idEleitor);  
                        vass.setVisible(true);  
                        this.dispose();
                    }
                }
                else {
                    if(facade.eleitorVotou(idEleitor)) JOptionPane.showMessageDialog(null, "Eleitor já efectou voto!");
                    else JOptionPane.showMessageDialog(null, "Tipo da eleição é inválido!");
                }

                }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ConsultarEcra cons = new ConsultarEcra(idEleitor,loginCandidato);  
        cons.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EcraEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EcraEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EcraEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EcraEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EcraEleitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/GUI/pictures/icom.png")));
    }
}
