/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Toolkit;
import Negocio3.Facade;

/**
 *
 * @author pedro
 */
public class PreRequesitos extends javax.swing.JFrame {

    /**
     * Creates new form PreRequesitos2
     */
    //String funcao;
    //private JanelaPrincipalCandidato jc;
    private final boolean anteriorPresidencial;
    private final int id;
 
    public PreRequesitos(Boolean pr,int id) {
        initComponents();
        setIcon();
         this.anteriorPresidencial = pr;
         this.id = id;
         
    }
    public PreRequesitos(){
        initComponents();
        setIcon();
        this.anteriorPresidencial = false;
        this.id = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestor de Eleições");
        getContentPane().setLayout(null);

        jLabel2.setText("Inscrição Candidato/Partido");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 60, 280, 14);

        jLabel3.setText("Indique as suas opções nos seguintes pré-requesitos ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 120, 550, 14);

        jButton1.setText("Prosseguir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(653, 500, 100, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(309, 190, 210, 30);

        jLabel4.setText("Votou em todas as Eleições?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 190, 220, 14);

        jLabel5.setText("É o seu terceiro mandato?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 260, 170, 14);

        jLabel6.setText("Tem registo criminal?");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 330, 170, 14);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(310, 260, 210, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(310, 330, 210, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/eleicoes.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 540);

        setSize(new java.awt.Dimension(785, 574));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
         //JanelaPrincipalCandidato jc = new JanelaPrincipalCandidato();
         //String funcao = jc.jComboBox1.getSelectedItem().toString();
         //String funcao = this.jcb.getSelectedItem().toString();
         //if(funcao.equals("Presidencial")){
         Facade facade = new Facade();
         if(this.anteriorPresidencial){
             facade.createPreRequisitos(id, jTextField1.getText(),jTextField2.getText(), jTextField3.getText());
             InscrevePresidencial inscpresi = new InscrevePresidencial(id);
             inscpresi.setVisible(true);
             this.dispose();
         }
         else{
               facade.createPreRequisitosPartidos(id, jTextField1.getText(),jTextField2.getText(), jTextField3.getText());
               InscreveAssembleia ia = new InscreveAssembleia(id);
               ia.setVisible(true);
               this.dispose();
         }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreRequesitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreRequesitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreRequesitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreRequesitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreRequesitos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/GUI/pictures/icom.png")));
    }
}
