/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import Negocio3.Facade;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pedro
 */
public class VotarAssembleia extends javax.swing.JFrame {
    Facade facade = new Facade();
    
    private final int idEleitor;
    /**
     * Creates new form VotarAssembleia2
     */
    public VotarAssembleia() {
        initComponents();
        setIcon();
        this.idEleitor = 0;
        povoarList();
        
    }

    public VotarAssembleia(int idEleitor)  {
        initComponents();
        setIcon();
        this.idEleitor = idEleitor;
        povoarList();
       
    }
    
    private void povoarList(){
        ArrayList<String> ec = (ArrayList<String>) facade.getListaPartidosEleicaoVotos();
        //DefaultListModel dlm = (DefaultListModel)this.jList1.getModel();
        DefaultListModel list = new DefaultListModel();
        //int i=-1; 
        for(String s : ec){
             list.addElement(s);
         }
        //this.jList1 = new JList(list);
        this.jList1.setModel(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestor de Eleições");
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Eleição Assembleia");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 10, 220, 20);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Partido X", "Partido Y", "Partido Z", "Partido A", "Partido B", "Partido C", "Partido D" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 210, 710, 170);

        jButton3.setText("Confirmar Voto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(640, 390, 120, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/parlamento_europeu_kerodicas.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 50, 520, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/eleicoes.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 430);

        setSize(new java.awt.Dimension(796, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
        String partidoescolhido = jList1.getSelectedValue().toString();
        System.out.println(partidoescolhido);
        int r = facade.idEleicaoAbertaAVtoto();
        System.out.println(r);
        int circulo = facade.getCirculoEleitoralEleitor(idEleitor);
        System.out.println(circulo);
        int escolha = facade.getIdListaParaVoto(idEleitor, r, partidoescolhido);
        System.out.println(escolha);
        System.out.println(facade.putVoto(r, escolha));
        facade.setEleitorVoto(idEleitor, true);
        facade.setCirculoEleitoralProvisorio(idEleitor, circulo);
        }
        catch (Exception ex){
            // VOTO NULO uuuh
            //Logger.getLogger(VotarAssembleia.class.getName()).log(Level.SEVERE, null, ex);
            facade.setEleitorVoto(idEleitor, true);
        int r = facade.idEleicaoAbertaAVtoto();
        facade.setVotoBranco(r);
        facade.setEleitorVoto(idEleitor, true);
        }
        finally {
        System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VotarAssembleia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VotarAssembleia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VotarAssembleia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VotarAssembleia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VotarAssembleia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/GUI/pictures/icom.png")));
    }
}
